package com.test;

class DatabaseStatements {
	static final String GET_ORDER_SUMMARIZED2 = "SELECT "
			+ "o.id AS Order_ID, "
			+ "o.timestamp AS order_timestamp, " + "o.status AS order_status, "
			+ "o.facility_id AS facility_id, "
			+ "sum(d.unit_price*unit_number(o.order_tup)) as total_costs "
			+ "FROM ("
				+ "SELECT facility_id,id,timestamp,status,unnest(order_arr) as order_tup "
				+ "FROM orders_new) o "
			+ "JOIN drugs d "
			+ "ON drug_id(o.order_tup) = d.id "
			+ "JOIN categories c "
			+ "ON c.id = d.category_id "
			+ "WHERE o.timestamp BETWEEN ? AND ? "
			+ "AND o.id = COALESCE(?,o.id) "
			+ "AND o.status = COALESCE(?,o.status) "
			+ "AND o.facility_id = COALESCE(?,o.facility_id) "
			+ "GROUP BY o.facility_id,o.id,o.timestamp,o.status "
			+ "ORDER BY o.id ASC";
	static final String GET_ORDER_NON_SUMMARIZED2 = "SELECT "
			+ "o.id AS Order_ID, "
			+ "o.timestamp AS order_timestamp, " + "o.status AS order_status, "
			+ "o.facility_id AS facility_id, "
			+ "array_to_json(array_agg(row_to_json((d.*,unit_number(o.order_tup))::drug_ext)))::text AS drugs "
			+ "FROM ("
				+ "SELECT facility_id,id,timestamp,status,unnest(order_arr) as order_tup "
				+ "FROM orders_new) o "
			+ "JOIN drugs d "
			+ "ON drug_id(o.order_tup) = d.id "
			+ "JOIN categories c "
			+ "ON c.id = d.category_id "
			+ "WHERE o.timestamp BETWEEN ? AND ? "
			+ "AND o.id = COALESCE(?,o.id) "
			+ "AND o.status = COALESCE(?,o.status) "
			+ "AND o.facility_id = COALESCE(?,o.facility_id) "
			+ "GROUP BY o.facility_id,o.id,o.timestamp,o.status "
			+ "ORDER BY o.id ASC";
//	static final String GET_ORDER_NON_SUMMARIZED = "SELECT "
//			+ "o.id AS Order_ID, "
//			+ "o.timestamp AS order_timestamp, " + "o.status AS order_status, "
//			+ "o.facility_id AS facility_id, "
//			+ "row_to_json((d.*,o.unit_number)::drug_ext)::text AS drug "
//			+ "FROM orders o JOIN drugs d "
//			+ "ON o.drug_id = d.id "
//			+ "JOIN categories c "
//			+ "ON c.id = d.category_id "
//			+ "WHERE o.timestamp BETWEEN ? AND ? "
//			+ "AND o.id = COALESCE(?,o.id) "
//			+ "AND o.status = COALESCE(?,o.status) "
//			+ "AND o.facility_id = COALESCE(?,o.facility_id) "
//			+ "ORDER BY o.id ASC";
//	
//
//	static final String GET_ORDER_SUMMARIZED = "SELECT DISTINCT "
//			+ "o.id AS Order_ID, "
//			+ "o.timestamp AS order_timestamp, " + "o.status AS order_status, "
//			+ "o.facility_id AS facility_id, "
//			+ "sum(d.unit_price*o.unit_number) as total_costs "
//			+ "FROM orders o JOIN drugs d "
//			+ "ON o.drug_id = d.id "
//			+ "JOIN categories c "
//			+ "ON c.id = d.category_id "
//			+ "WHERE o.timestamp BETWEEN ? AND ? "
//			+ "AND o.id = COALESCE(?,o.id) "
//			+ "AND o.status = COALESCE(?,o.status) "
//			+ "AND o.facility_id = COALESCE(?,o.facility_id) "
//			+ "GROUP BY o.id, o.timestamp, o.status, o.facility_id "
//			+ "ORDER BY o.id ASC";
	
	static final String ADD_ORDER_NEW = "INSERT INTO "
					+ "orders_new (id,facility_id,timestamp,status,order_arr) "
					+ "VALUES (default,?,now(),?,?)";
	
	
}
